project_id = "bcobgfxepxmmcheuliai"

[functions.ai-generate-script]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-generate-image]
verify_jwt = false

[functions.ai-analyze-image]
verify_jwt = false
